### ISSUE TITLE
Can you add support for arm64 architecture

### ISSUE THREAD

**Issue by hsleewis** [st3fan/mijia-hub#3]
Just tried to install the package on my new Pi 4 (running ubuntu)
`dpkg: error processing archive mijia-hub_0.2.0_armhf.deb (--install): package architecture (armhf) does not match system (arm64)`

**Comment by st3fan** [comment]
Sorry for the delay - this should be easy. I'll publish a Linux/arm64 package for `0.2.0`.

**Comment by st3fan** [comment]
I updated the build script to create both armhf and arm64 packages and added a 0.2.0 arm64 to the release page.

**Comment by hsleewis** [comment]
Thanks, a bit late, but just installed it, I get this error when trying to start the mijia-hub:
`Failed to start mijia-hub.service: Unit hciuart.service not found.`
Any idea how I can fix that?
